packages:
  - apps/*
  - packages/*
catalog:
  "@next/eslint-plugin-next": ^14.2.3
  "@types/node": ^20.11.24
  "@types/react": ^18.2.61
  "@types/react-dom": ^18.2.19
  "@vercel/style-guide": ^5.2.0
  autoprefixer: ^10.4.18
  eslint-config-turbo: ^2.0.0
  next: ^14.2.3
  postcss: ^8.4.35
  prettier: ^3.2.5
  prettier-plugin-tailwindcss: ^0.5.11
  react: ^18.2.0
  react-dom: ^18.2.0
  tailwindcss: ^3.4.1
  turbo: ^2.3.3
  typescript: 5.5.4
